### ISSUE TITLE
Code used to benchmark

### ISSUE THREAD

**Issue by sen-pai** [JLSteenwyk/ClipKIT#41]
Thanks for this really useful library! 
I'm trying to find the code you have used to compare ClipKIT with other methods (the graphs shown [here](https://jlsteenwyk.com/ClipKIT/performance_assessment/index.html#benchmarking)). 

if you have written any wrappers around trimAI, Gblocks (whose source code I cant seem to find) and BMGE, could you please share them too?

**Comment by JLSteenwyk** [comment]
Hi @sen-pai,

Thank you for writing and for using ClipKIT!

With respect to the desirability-based framework for ranking, I used the general framework detailed, including R code, here: [integRATE](https://github.com/haleyeidem/integRATE) from [Eidem et al. (2018) BMC Medical Genomics](https://bmcmedgenomics.biomedcentral.com/articles/10.1186/s12920-018-0426-y).

For trimAl, I used:
`trimal -in <inputfile> -out <outputfile> -gappyout`;
`trimal -in <inputfile> -out <outputfile> -strict`; and
`trimal -in <inputfile> -out <outputfile> -strictplus`.

For GBlocks, I used default parameters. I, too, am having trouble finding the source code since the original domain seems to be stalling. However, I found this link to a web portal version [http://phylogeny.lirmm.fr/phylo_cgi/one_task.cgi?task_type=gblocks](http://phylogeny.lirmm.fr/phylo_cgi/one_task.cgi?task_type=gblocks).

I hope this helps!
